// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9tEAXFMYG6N9eBtCh6R-kWpncecud7cU',
    appId: '1:95955724711:web:9158faaf62504971cfae82',
    messagingSenderId: '95955724711',
    projectId: 'mobiletest-69a35',
    authDomain: 'mobiletest-69a35.firebaseapp.com',
    storageBucket: 'mobiletest-69a35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeGDFw3JPrzvVOLmrqGzH9oIWUQYDmrpg',
    appId: '1:95955724711:android:0246cf1b7cf601b8cfae82',
    messagingSenderId: '95955724711',
    projectId: 'mobiletest-69a35',
    storageBucket: 'mobiletest-69a35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhbrSZLltgRUv12Bo6JVkAANN7--D21EM',
    appId: '1:95955724711:ios:c520f97da7d8f625cfae82',
    messagingSenderId: '95955724711',
    projectId: 'mobiletest-69a35',
    storageBucket: 'mobiletest-69a35.appspot.com',
    androidClientId: '95955724711-k3hqatvnhtbm08pvidcgbmres3iocvcv.apps.googleusercontent.com',
    iosClientId: '95955724711-rvsa917qcgn0pmkfp1n854vb8b8ino9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.uiwithcomponent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhbrSZLltgRUv12Bo6JVkAANN7--D21EM',
    appId: '1:95955724711:ios:153f292cf5b306f9cfae82',
    messagingSenderId: '95955724711',
    projectId: 'mobiletest-69a35',
    storageBucket: 'mobiletest-69a35.appspot.com',
    androidClientId: '95955724711-k3hqatvnhtbm08pvidcgbmres3iocvcv.apps.googleusercontent.com',
    iosClientId: '95955724711-931fu0fl4945qbck1fft4539bl8ueb6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.uiwithcomponent.RunnerTests',
  );
}
